DOCUMENTATIONS: Task3 Q&A
GulchexrasGithub/Gulchekhra_Burkhonova_INDIVIDUAL_MENTORSHIP pull request #6
Opened 2023-06-10 08:49 UTC by GulchexrasGithub

Closes #4 , #5

2023-06-14 08:42 UTC, FirdavsExadel requested changes

2023-06-14 08:42 UTC, FirdavsExadel commented on Projects/WeatherForecast.BL/Services/WeatherService.cs
> +            if (temperature < 0)
replace if and else with switch expressions

2023-06-14 08:42 UTC, FirdavsExadel commented on Projects/WeatherForecast.Core/Repository/WeatherRepository.cs
> +            throw new NotImplementedException();
please you use this api 
https://www.weatherapi.com/docs/

2023-06-20 11:13 UTC, GulchexrasGithub commented
@FirdavsExadel Hello, Can you have a look please? The WeahterForecast project is working well, if you merge it then I can do test

2023-06-20 11:41 UTC, FirdavsExadel approved these changes

2023-06-20 13:15 UTC, merged